import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, Copy, Ear, ImagePlus, LockKeyhole, LogOut, MessageCircle, Plus, Send, Settings, ShieldCheck, Sparkles, Trash2, UserMinus, Users, X } from 'lucide-react';
import './coda.css';
import { CodaMessageContent } from './CodaMessageContent';
type User = { id: string; name: string };
type Room = { id: string; owner: string; title: string; mode: 'reply' | 'listen' };
type RoomImage = { id: string; filename: string; alt: string; mime: string; size: number; width: number; height: number; url: string };
type Message = { seq: number; author: string; name: string; content: string; created: number; images: RoomImage[] };
type Detail = { room: Room; messages: Message[]; members: User[]; busy: boolean };
type PendingImage = { file: File; preview: string; alt: string };
type MemoryView = { linked: boolean; profile: Record<string, unknown> | null; notes: Array<{id:string;content:string;visibility:string;kind:string}> };
async function api<T>(path: string, method = 'GET', data?: unknown): Promise<T> {
  const response = await fetch('/coda/api' + path, { method, headers: { 'Content-Type': 'application/json' }, ...(data === undefined ? {} : { body: JSON.stringify(data) }) });
  const result = await response.json().catch(() => ({ error: 'Coda’s room server is not available yet.' }));
  if (!response.ok) throw new Error(result.error || 'Something went wrong. Try again.');
  return result;
}
export function Coda() {
  const [user, setUser] = useState<User | null>(null); const [ready, setReady] = useState(false);
  const [configured, setConfigured] = useState(false); const [providerReady, setProviderReady] = useState(false);
  const [rooms, setRooms] = useState<Room[]>([]); const [active, setActive] = useState(''); const [detail, setDetail] = useState<Detail | null>(null);
  const [text, setText] = useState(''); const [error, setError] = useState(''); const [pending, setPending] = useState(false); const [working, setWorking] = useState(false);
  const [newRoom, setNewRoom] = useState(false); const [title, setTitle] = useState(''); const [invite, setInvite] = useState(''); const [inviteCopied, setInviteCopied] = useState(false);
  const [showMembers, setShowMembers] = useState(false); const [showSettings, setShowSettings] = useState(false); const [rename, setRename] = useState(''); const [mobileRooms, setMobileRooms] = useState(false); const [joining, setJoining] = useState(false);
  const [command, setCommand] = useState<'help'|'format'|'memory'|'clear'|''>(''); const [memory, setMemory] = useState<MemoryView | null>(null); const [memoryText, setMemoryText] = useState(''); const [memoryVisibility, setMemoryVisibility] = useState('private'); const [pendingImages, setPendingImages] = useState<PendingImage[]>([]);
  const bottom = useRef<HTMLDivElement>(null); const imageInput = useRef<HTMLInputElement>(null); const activeRef = useRef(''); activeRef.current = active;
  const inviteToken = useRef(new URLSearchParams(location.hash.slice(1)).get('invite') || sessionStorage.getItem('coda-invite') || '');
  useEffect(() => {
    document.title = 'Coda’s Den · Howling Whispers';
    let meta = document.querySelector('meta[name="robots"]'); if (!meta) { meta = document.createElement('meta'); meta.setAttribute('name','robots'); document.head.append(meta); } meta.setAttribute('content','noindex, nofollow, noarchive');
    document.querySelector('link[rel="canonical"]')?.remove();
    if (inviteToken.current) { sessionStorage.setItem('coda-invite',inviteToken.current); history.replaceState(null,'','/coda'); }
    api<{user: User|null; configured: boolean; providerReady: boolean}>('/me').then(data => { setUser(data.user); setConfigured(data.configured); setProviderReady(data.providerReady); }).catch(e=>setError(e.message)).finally(()=>setReady(true));
  },[]);
  async function refreshRooms() { const data = await api<{rooms: Room[]}>('/rooms'); setRooms(data.rooms); return data.rooms; }
  async function refresh(id: string) { const data = await api<Detail>('/rooms/'+id); if (activeRef.current === id) setDetail(data); }
  useEffect(() => { if (user && inviteToken.current) setJoining(true); if (user) refreshRooms().then(list=>{if (!activeRef.current && list.length) setActive(list[0].id);}).catch(e=>setError(e.message)); },[user]);
  useEffect(()=>{
    if (!active) { setDetail(null); return; }
    setDetail(null); setInvite(''); setShowMembers(false); setShowSettings(false); setCommand(''); setPendingImages(previous=>{previous.forEach(image=>URL.revokeObjectURL(image.preview));return [];}); setError('');
    let canceled = false;
    const load = () => api<Detail>('/rooms/'+active).then(data=>{if(!canceled) setDetail(data);}).catch(e=>{if(!canceled) setError(e.message);});
    void load(); const interval = setInterval(load,2500); return ()=>{canceled=true; clearInterval(interval);};
  },[active]);
  useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth'});},[detail?.messages.length,working]);
  async function perform(fn:()=>Promise<void>) { setError(''); setPending(true); try { await fn(); } catch(e) { setError((e as Error).message); } finally { setPending(false); } }
  async function ask(id: string) { setWorking(true); try { await api('/rooms/'+id+'/reply','POST'); await refresh(id); } finally { setWorking(false); } }
  async function openMemory() { const data=await api<MemoryView>('/memory');setMemory(data);setCommand('memory'); }
  async function handleCommand(value:string) { const name=value.trim().split(/\s+/)[0].toLowerCase();if(name==='/help')setCommand('help');else if(name==='/format')setCommand('format');else if(name==='/memory')await openMemory();else if(name==='/clear')setCommand('clear');else throw new Error('Unknown Coda command. Use /help to see available commands.');setText(''); }
  function selectImages(files:File[]) { setError('');const accepted=files.filter(file=>['image/png','image/jpeg','image/webp'].includes(file.type)&&file.size<=8*1024*1024).slice(0,Math.max(0,4-pendingImages.length));if(accepted.length!==files.length)setError('Use up to four PNG, JPEG, or WebP images, 8 MiB each.');setPendingImages(previous=>[...previous,...accepted.map(file=>({file,preview:URL.createObjectURL(file),alt:''}))]); }
  async function send() {
    if(!detail || pending || working || detail.busy || (!text.trim()&&!pendingImages.length)) return; const id=active; const message=text; const images=pendingImages;
    await perform(async()=>{if(message.trim().startsWith('/')&&!images.length){await handleCommand(message);return;}const uploaded:RoomImage[]=[];try{for(const image of images){const response=await fetch(`/coda/api/rooms/${id}/images`,{method:'POST',headers:{'Content-Type':image.file.type,'X-Coda-Filename':encodeURIComponent(image.file.name),'X-Coda-Alt':encodeURIComponent(image.alt)},body:image.file});const data=await response.json();if(!response.ok)throw new Error(data.error||'That image could not be uploaded.');uploaded.push(data.image);}await api('/rooms/'+id+'/messages','POST',{text:message,imageIds:uploaded.map(image=>image.id)});}catch(error){await Promise.all(uploaded.map(image=>api(`/rooms/${id}/images/${image.id}`,'DELETE').catch(()=>undefined)));throw error;}setText('');setPendingImages([]);images.forEach(image=>URL.revokeObjectURL(image.preview));await refresh(id);if(detail.room.mode==='reply'&&!detail.busy)await ask(id);});
  }
  useEffect(() => {
    if (!newRoom && !invite && !joining && !showMembers && !showSettings && !command) return;
    const previous = document.activeElement as HTMLElement | null;
    const dialog = document.querySelector<HTMLElement>('[role="dialog"]');
    const controls = () => Array.from(dialog?.querySelectorAll<HTMLElement>('button:not(:disabled), input, textarea, [tabindex="0"]') || []);
    (dialog?.querySelector<HTMLElement>('input') || controls()[0])?.focus();
    const trap = (event: KeyboardEvent) => {
      if (event.key === 'Escape') { setNewRoom(false); setInvite(''); setJoining(false); setShowMembers(false); setShowSettings(false); setCommand(''); }
      if (event.key !== 'Tab') return;
      const list = controls(); const first = list[0]; const last = list[list.length - 1];
      if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); }
      else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); }
    };
    document.addEventListener('keydown', trap);
    return () => { document.removeEventListener('keydown', trap); previous?.focus(); };
  }, [newRoom, invite, joining, showMembers, showSettings, command]);
  const owner = detail?.room.owner===user?.id;
  const signIn = () => { location.href='/coda/api/login'; };
  return <div className="coda-app">
    <aside className={'coda-sidebar '+(mobileRooms?'is-open':'')} aria-label="Conversations">
      <a className="coda-brand" href="/coda"><span className="coda-paw">🐾</span><span>Coda’s Den<small>HOWLING WHISPERS</small></span></a>
      <button className="coda-new" onClick={()=>{setNewRoom(true);setMobileRooms(false);}} disabled={!user}><Plus size={18}/> New conversation</button>
      <div className="coda-side-label">YOUR CONVERSATIONS</div>
      <nav>{rooms.map(room=><button key={room.id} className={'coda-room '+(active===room.id?'selected':'')} onClick={()=>{setActive(room.id);setMobileRooms(false);}}><MessageCircle size={17}/><span>{room.title}</span></button>)}</nav>
      {!rooms.length && <p className="coda-side-empty">A quiet corner, just for you.<br/>Your conversations will live here.</p>}
      <div className="coda-sidebar-bottom"><div className="coda-private"><ShieldCheck size={18}/><span>Private by invitation<small>Only room members can read it.</small></span></div><a href="/"><ArrowLeft size={16}/> Welcome hub</a>{user && <button onClick={()=>perform(async()=>{await api('/logout','POST');location.reload();})}><LogOut size={16}/> Sign out · {user.name}</button>}</div>
    </aside>
    {mobileRooms && <button className="coda-scrim" aria-label="Close conversations" onClick={()=>setMobileRooms(false)}/>}
    <main className="coda-main">
      <header className="coda-header"><button className="coda-mobile-menu" aria-label="Open conversations" onClick={()=>setMobileRooms(true)}><MessageCircle size={21}/></button><div><h1>{detail?.room.title || 'A little room for big ideas'}</h1><span><LockKeyhole size={13}/> {detail ? `${detail.members.length} ${detail.members.length===1?'person':'people'} + Coda` : 'Your private corner of Howling Whispers'}</span></div>{detail && <div className="coda-room-actions"><button onClick={()=>{setRename(detail.room.title);setShowSettings(true);}} aria-label="Conversation settings"><Settings size={18}/><span>Settings</span></button><button onClick={()=>setShowMembers(!showMembers)} aria-label="Room members"><Users size={18}/><span>Members</span></button>{owner && <button onClick={()=>perform(async()=>{const data=await api<{url:string}>('/rooms/'+active+'/invite','POST');setInvite(data.url);setInviteCopied(false);})} disabled={pending}><Plus size={17}/><span>Invite friend</span></button>}</div>}</header>
      <div className="coda-conversation">
        {!detail && <section className="coda-welcome"><div className="coda-avatar large">🐾</div><p className="coda-eyebrow">COME IN. GET COMFY.</p><h2>Well, hello there.</h2><p>Questions, wild ideas, a stubborn bug?<br/>Pull up a chair. My ears are listening.</p><div className="coda-welcome-note"><LockKeyhole size={18}/><span>Start a conversation with me, or invite a friend into your own little den.</span></div>{!ready ? <p role="status">Opening the den…</p> : !user ? <button className="coda-primary" disabled={!configured} onClick={signIn}>Sign in with Discord</button> : <button className="coda-primary" onClick={()=>inviteToken.current?setJoining(true):setNewRoom(true)}>{inviteToken.current?'Open your invitation':'Start a conversation'}</button>}{ready && !configured && <p className="coda-muted">The den is waiting for its sign-in connection.</p>}{user && inviteToken.current && !joining && <button onClick={()=>setJoining(true)}>Review invitation</button>}</section>}
        {detail && <><div className="coda-room-intro"><span>🐾</span><div><strong>Coda is here.</strong><p>This room has its own conversation history. Coda may still remember things you’ve shared with her elsewhere, subject to your memory and privacy settings.</p></div></div>{detail.messages.map(message=><article className={'coda-message '+(message.author==='coda'?'from-coda':'')} key={message.seq}><div className="coda-avatar">{message.author==='coda'?'🐾':message.name.slice(0,1).toUpperCase()}</div><div className="coda-message-body"><div className="coda-message-meta"><strong>{message.name}</strong>{message.author==='coda' && <span className="coda-badge">CODA</span>}<time dateTime={new Date(message.created).toISOString()}>{new Date(message.created).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time></div>{message.content && <CodaMessageContent content={message.content}/>} {!!message.images?.length && <div className="coda-image-grid">{message.images.map(image=><a key={image.id} href={image.url} target="_blank" rel="noopener noreferrer"><img src={image.url} alt={image.alt || image.filename} width={image.width} height={image.height} loading="lazy" decoding="async" referrerPolicy="no-referrer"/><span>{image.alt || image.filename}</span></a>)}</div>}<button className="coda-copy" aria-label="Copy message" onClick={()=>perform(async()=>{await navigator.clipboard.writeText(message.content);})}><Copy size={14}/> Copy</button></div></article>)}{(working || detail.busy) && <div className="coda-thinking" role="status"><Sparkles size={17}/> Coda is thinking… <span>Give those canine brain cells a moment.</span></div>}<div ref={bottom}/></>}
      </div>
      {error && <div className="coda-error" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
      {detail && <footer className="coda-composer-area"><div className="coda-composer-top"><span><Ear size={15}/> {detail.room.mode==='listen'?'Just listening':'Coda replies after you send'}</span><div>{owner && <button disabled={pending} onClick={()=>perform(async()=>{await api('/rooms/'+active,'PATCH',{mode:detail.room.mode==='reply'?'listen':'reply'});await refresh(active);})}>{detail.room.mode==='reply'?'Just listen':'Join in'}</button>}<button disabled={pending || working || detail.busy || !providerReady} onClick={()=>perform(()=>ask(active))}>Ask Coda</button></div></div>{!!pendingImages.length && <div className="coda-image-previews">{pendingImages.map((image,index)=><div key={image.preview}><img src={image.preview} alt="Selected preview"/><input aria-label={`Alt text for ${image.file.name}`} value={image.alt} maxLength={500} placeholder="Describe this image for accessibility" onChange={event=>setPendingImages(previous=>previous.map((item,itemIndex)=>itemIndex===index?{...item,alt:event.target.value}:item))}/><button aria-label={`Remove ${image.file.name}`} onClick={()=>setPendingImages(previous=>previous.filter((item,itemIndex)=>{if(itemIndex===index)URL.revokeObjectURL(item.preview);return itemIndex!==index;}))}><X size={15}/></button></div>)}</div>}<form className="coda-composer" onSubmit={e=>{e.preventDefault();void send();}}><input ref={imageInput} className="coda-file-input" type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={event=>{selectImages(Array.from(event.target.files||[]));event.target.value='';}}/><button type="button" className="coda-attach" aria-label="Attach images" onClick={()=>imageInput.current?.click()} disabled={pending || pendingImages.length>=4}><ImagePlus size={19}/></button><textarea aria-label="Message" placeholder={detail.room.mode==='listen'?'Chat with your friend. Coda is listening…':'What’s on your mind?'} value={text} onChange={e=>setText(e.target.value)} onPaste={event=>{const files=Array.from(event.clipboardData.files).filter(file=>file.type.startsWith('image/'));if(files.length){event.preventDefault();selectImages(files);}}} onKeyDown={e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();void send();}}} maxLength={8000} rows={3}/><button className="coda-send" disabled={pending || (!text.trim()&&!pendingImages.length)} type="submit" aria-label="Send message"><Send size={19}/></button></form><p className="coda-composer-note">Enter makes a new line, Ctrl/⌘ + Enter sends · paste or attach up to 4 images · /help for commands · {providerReady?'Powered by Kilo':'Kilo connection pending'}{text.length>7200 && ` · ${8000-text.length} characters left`}</p></footer>}
    </main>
    {newRoom && <div className="coda-modal-backdrop"><form role="dialog" aria-modal="true" aria-label="New conversation" className="coda-modal" onSubmit={e=>{e.preventDefault();void perform(async()=>{const data=await api<{id:string}>('/rooms','POST',{title});await refreshRooms();setActive(data.id);setNewRoom(false);setTitle('');});}}><button type="button" className="coda-modal-close" aria-label="Close" onClick={()=>setNewRoom(false)}><X/></button><span className="coda-eyebrow">A FRESH LITTLE DEN</span><h2>Name your conversation</h2><label htmlFor="room-title">Room name</label><input id="room-title" autoFocus maxLength={80} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ideas over bacon" required/><p>It starts with you and Coda. You can invite a friend whenever you like.</p>{error && <p role="alert" className="coda-modal-error">{error}</p>}<button className="coda-primary" disabled={pending || !title.trim()}>Create conversation</button></form></div>}
    {invite && <div className="coda-modal-backdrop"><section role="dialog" aria-modal="true" aria-label="Room controls" className="coda-modal"><button className="coda-modal-close" aria-label="Close" onClick={()=>setInvite('')}><X/></button><span className="coda-eyebrow">MAKE ROOM FOR A FRIEND</span><h2>One invitation. One friend.</h2><p>Valid for 24 hours and one use. Your guest can read this room’s earlier messages. Share it only with the person you want here.</p><input aria-label="Invitation link" readOnly value={invite} onFocus={e=>e.target.select()}/><button className="coda-primary" onClick={()=>perform(async()=>{await navigator.clipboard.writeText(invite);setInviteCopied(true);})}>{inviteCopied?'Copied':'Copy invitation'}</button><button onClick={()=>perform(async()=>{await api('/rooms/'+active+'/invite','DELETE');setInvite('');})}>Revoke unused invitations</button></section></div>}
    {joining && <div className="coda-modal-backdrop"><section role="dialog" aria-modal="true" aria-label="Room controls" className="coda-modal"><button className="coda-modal-close" aria-label="Close" onClick={()=>setJoining(false)}><X/></button><h2>You’ve been invited.</h2><p>Joining gives you access to the room’s history. Your messages will be visible to its members and used as context for Coda’s replies.</p>{error && <p role="alert" className="coda-modal-error">{error}</p>}<button className="coda-primary" disabled={pending} onClick={()=>perform(async()=>{const data=await api<{id:string}>('/join','POST',{token:inviteToken.current});sessionStorage.removeItem('coda-invite');inviteToken.current='';await refreshRooms();setActive(data.id);setJoining(false);})}>Join conversation</button></section></div>}
    {showMembers && detail && <div className="coda-modal-backdrop"><section role="dialog" aria-modal="true" aria-label="Room members" className="coda-modal"><button className="coda-modal-close" aria-label="Close" onClick={()=>setShowMembers(false)}><X/></button><h2>Who’s in the den?</h2>{detail.members.map(member=><div className="coda-member" key={member.id}><span>{member.name}{member.id===detail.room.owner?' · Host':''}</span>{owner && member.id!==user?.id && <button onClick={()=>perform(async()=>{await api('/rooms/'+active+'/members','DELETE',{userId:member.id});await refresh(active);})}>Remove</button>}</div>)}<div className="coda-member"><span>🐾 Coda</span><span>Assistant</span></div><button className="coda-secondary" onClick={()=>{setShowMembers(false);setRename(detail.room.title);setShowSettings(true);}}>Conversation settings</button></section></div>}
    {showSettings && detail && <div className="coda-modal-backdrop"><section role="dialog" aria-modal="true" aria-label="Conversation settings" className="coda-modal"><button type="button" className="coda-modal-close" aria-label="Close" onClick={()=>setShowSettings(false)}><X/></button><span className="coda-eyebrow">CONVERSATION SETTINGS</span><h2>{detail.room.title}</h2>{error && <p role="alert" className="coda-modal-error">{error}</p>}{owner ? <><label htmlFor="room-rename">Conversation name</label><input id="room-rename" maxLength={80} value={rename} onChange={e=>setRename(e.target.value)}/><button className="coda-primary" disabled={pending || !rename.trim() || rename.trim()===detail.room.title} onClick={()=>perform(async()=>{await api('/rooms/'+active,'PATCH',{title:rename});await refresh(active);await refreshRooms();setShowSettings(false);})}>Save name</button><p>Renaming only changes the label. The host still controls invitations and deletion.</p></> : <p>You joined this conversation by invitation. Only the host can rename or delete it, but you can leave it yourself.</p>}{owner ? <button className="coda-danger" disabled={pending || working || detail.busy} onClick={()=>{if(confirm('Delete this conversation and its entire history for everyone?'))void perform(async()=>{await api('/rooms/'+active,'DELETE');const list=await refreshRooms();setActive(list[0]?.id || '');setShowSettings(false);setShowMembers(false);});}}><Trash2 size={15}/> Delete conversation</button> : <button className="coda-danger" disabled={pending || working || detail.busy} onClick={()=>perform(async()=>{await api('/rooms/'+active+'/members','DELETE',{userId:user?.id});const list=await refreshRooms();setActive(list[0]?.id || '');setShowSettings(false);setShowMembers(false);})}><UserMinus size={15}/> Leave conversation</button>}<p className="coda-danger-note">{owner?'Deleting removes this conversation and its entire history for everyone, including invited friends.':'Leaving removes you from this conversation. The host keeps it and its history.'}</p></section></div>}
    {command==='help' && <div className="coda-modal-backdrop"><section role="dialog" aria-modal="true" aria-label="Coda commands" className="coda-modal"><button className="coda-modal-close" aria-label="Close" onClick={()=>setCommand('')}><X/></button><span className="coda-eyebrow">BROWSER CODA COMMANDS</span><h2>Commands</h2><dl className="coda-command-list"><dt>/help</dt><dd>Show this private command guide.</dd><dt>/memory</dt><dd>View and manage memory for your authenticated Discord account.</dd><dt>/format</dt><dd>Show supported Markdown and semantic colors.</dd><dt>/clear</dt><dd>Clear this room’s transcript after confirmation. Host-only and unavailable while guests remain.</dd></dl><p>Commands are handled privately and are never stored in the room transcript or sent to Coda.</p></section></div>}
    {command==='format' && <div className="coda-modal-backdrop"><section role="dialog" aria-modal="true" aria-label="Formatting guide" className="coda-modal"><button className="coda-modal-close" aria-label="Close" onClick={()=>setCommand('')}><X/></button><span className="coda-eyebrow">SAFE FORMATTING</span><h2>Markdown and colors</h2><CodaMessageContent content={'**bold**, *italics*, headings, lists, > quotes, `inline code`, fenced code blocks, and safe http/https links are supported.\n\nSemantic color: `:color[Canon note]{tone=canon}`\n\nApproved tones: canon, warning, conflict, speaker, note, muted.'}/><p>Raw HTML, remote Markdown images, scripts, arbitrary CSS, and unapproved colors are never rendered.</p></section></div>}
    {command==='memory' && <div className="coda-modal-backdrop"><section role="dialog" aria-modal="true" aria-label="Coda memory" className="coda-modal coda-memory-modal"><button className="coda-modal-close" aria-label="Close" onClick={()=>setCommand('')}><X/></button><span className="coda-eyebrow">YOUR CODA MEMORY</span><h2>What Coda may remember</h2>{!memory?.linked ? <p>This Discord account is not linked to an Orbis memory profile yet. Coda will answer without personal memory.</p> : <><div className="coda-memory-list">{memory.notes.length?memory.notes.map(note=><article key={note.id}><CodaMessageContent content={note.content}/><span>{note.visibility}</span><button onClick={()=>perform(async()=>{await api('/memory/forget','POST',{noteId:note.id});await openMemory();})}>Forget</button></article>):<p>No active memories yet.</p>}</div><form onSubmit={event=>{event.preventDefault();void perform(async()=>{await api('/memory/notes','POST',{content:memoryText,visibility:memoryVisibility});setMemoryText('');await openMemory();});}}><label htmlFor="memory-text">Add something you want Coda to remember</label><textarea id="memory-text" maxLength={4000} required value={memoryText} onChange={event=>setMemoryText(event.target.value)}/><label htmlFor="memory-visibility">Privacy</label><select id="memory-visibility" value={memoryVisibility} onChange={event=>setMemoryVisibility(event.target.value)}><option value="private">Private</option><option value="shared">Shared</option><option value="public">Public/shared rooms</option></select><button className="coda-primary" disabled={pending||!memoryText.trim()}>Remember this</button></form></>}</section></div>}
    {command==='clear' && detail && <div className="coda-modal-backdrop"><section role="dialog" aria-modal="true" aria-label="Clear conversation" className="coda-modal"><button className="coda-modal-close" aria-label="Close" onClick={()=>setCommand('')}><X/></button><span className="coda-eyebrow">CLEAR THIS CONTEXT</span><h2>Clear this room’s conversation history?</h2><p>This permanently removes only this room’s messages and attached images. It does not erase your Coda memory or any other room.</p>{!owner?<p className="coda-modal-error">Only the host can clear this room.</p>:detail.members.length>1?<p className="coda-modal-error">Shared history cannot be silently cleared. Remove invited members or create a new room first.</p>:<button className="coda-danger" disabled={pending||working||detail.busy} onClick={()=>perform(async()=>{await api('/rooms/'+active+'/clear','DELETE');await refresh(active);setCommand('');})}><Trash2 size={15}/> Confirm clear history</button>}</section></div>}
  </div>;
}
